// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq4xbFA1re9nvDw6aAfLvFGkqHuRRF4uw',
    appId: '1:712546475015:web:ca296326cc7a138d559ea2',
    messagingSenderId: '712546475015',
    projectId: 'gif-characters',
    authDomain: 'gif-characters.firebaseapp.com',
    storageBucket: 'gif-characters.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9_aJSdwACnY-lh96eQM60w8tyO2_zDmw',
    appId: '1:712546475015:android:e3b98f43e52707b7559ea2',
    messagingSenderId: '712546475015',
    projectId: 'gif-characters',
    storageBucket: 'gif-characters.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUUfr1j1R-y8TeQtHCsO9LBuSI1BKkFbA',
    appId: '1:712546475015:ios:63ef2bb994f331b0559ea2',
    messagingSenderId: '712546475015',
    projectId: 'gif-characters',
    storageBucket: 'gif-characters.appspot.com',
    iosBundleId: 'com.example.gifSkill',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUUfr1j1R-y8TeQtHCsO9LBuSI1BKkFbA',
    appId: '1:712546475015:ios:63ef2bb994f331b0559ea2',
    messagingSenderId: '712546475015',
    projectId: 'gif-characters',
    storageBucket: 'gif-characters.appspot.com',
    iosBundleId: 'com.example.gifSkill',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBq4xbFA1re9nvDw6aAfLvFGkqHuRRF4uw',
    appId: '1:712546475015:web:d3be3ebf7ac8c9e8559ea2',
    messagingSenderId: '712546475015',
    projectId: 'gif-characters',
    authDomain: 'gif-characters.firebaseapp.com',
    storageBucket: 'gif-characters.appspot.com',
  );
}
